# Generated by Django 3.1.14 on 2022-01-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20220111_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='картинка'),
            preserve_default=False,
        ),
    ]
